
CREATE TABLE IF NOT EXISTS clean_store_transactions (
    STORE_ID NVARCHAR(50),
    STORE_LOCATION NVARCHAR(50),
    PRODUCT_CATEGORY NVARCHAR(50),
    PRODUCT_ID INT,
    MRP FLOAT,
    CP FLOAT,
    DISCOUNT FLOAT,
    SP FLOAT,
    txn_date DATE
);
